name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v5
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install --no-fund --no-optional
      - name: run eslint
        run: npm run eslint
      - name: Build project
        run: npm run startw
